# Generated by Django 4.2.7 on 2023-12-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('Type1', 'Standard Email'), ('Type2', 'Phishing Email')], max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('scheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('TypeA', 'Type A'), ('TypeB', 'Type B')], max_length=50)),
                ('email_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='email_images/')),
                ('button', models.CharField(blank=True, max_length=50, null=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailGenerator.emailtemplate')),
            ],
        ),
    ]
