# Generated by Django 4.2.7 on 2023-12-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0002_remove_emailtemplate_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_sents',
            field=models.IntegerField(default=0),
        ),
    ]
