# Generated by Django 4.2.7 on 2023-12-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0003_emailtemplate_email_sents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='department_list',
        ),
    ]
