# Generated by Django 4.2.7 on 2023-12-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0004_remove_emailtemplate_department_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_subjectline',
            field=models.CharField(max_length=50),
        ),
    ]
