# Generated by Django 4.2.7 on 2023-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0006_emailtemplate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
