# Generated by Django 4.2.7 on 2023-12-12 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_employee_date_created'),
        ('emailGenerator', '0007_alter_emailtemplate_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
