# Generated by Django 4.2.7 on 2024-01-09 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0010_alter_emailtemplate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
