# Generated by Django 4.2.7 on 2024-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0011_alter_emailtemplate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
