# Generated by Django 4.2.7 on 2024-01-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0012_emailtemplate_is_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
