# Generated by Django 4.2.7 on 2024-01-15 08:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_departments_number_of_employees'),
        ('emailGenerator', '0014_sentemail_rename_emailtemplate_emaildocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='CTA_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='body_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.departments'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='email_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emailGenerator.emaildocument'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemail',
            name='image_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='link_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='nr_of_copies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='reported',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemail',
            name='theme',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentemail',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
