# Generated by Django 4.2.7 on 2024-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0015_sentemail_cta_clicks_sentemail_body_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildocument',
            name='email_theme',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
