# Generated by Django 4.2.7 on 2024-01-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_usescenario_company'),
        ('emailGenerator', '0016_emaildocument_email_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('scenario_type', models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('COLD', 'Cold'), ('OTHER', 'Other')], max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('scenario', models.TextField(help_text='Write a scenario where an email will be sent..')),
                ('POI', models.CharField(help_text='Person of Interest', max_length=255)),
                ('poi_email', models.EmailField(max_length=254)),
                ('link_field', models.URLField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.AlterField(
            model_name='emaildocument',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='emailGenerator.usescenario'),
        ),
    ]
