# Generated by Django 4.2.7 on 2024-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0017_usescenario_alter_emaildocument_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=40)),
                ('article_text', models.TextField()),
            ],
        ),
    ]
