# Generated by Django 4.2.7 on 2024-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0018_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usescenario',
            name='scenario_type',
        ),
        migrations.AddField(
            model_name='emaildocument',
            name='email_type',
            field=models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('COLD', 'Cold'), ('OTHER', 'Other')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
