# Generated by Django 4.2.7 on 2024-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0019_remove_usescenario_scenario_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildocument',
            name='email_type',
            field=models.CharField(choices=[('PROMOTIONAL', 'Promotional'), ('COLD', 'Cold'), ('OTHER', 'Other')], max_length=25),
        ),
    ]
