# Generated by Django 4.2.7 on 2024-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailGenerator', '0020_alter_emaildocument_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildocument',
            name='tracking_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
