# Generated by Django 4.2.7 on 2024-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
