# Generated by Django 4.2.7 on 2023-12-06 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('departments', models.TextField(blank=True, help_text='Enter a comma-separated list of department names')),
                ('img', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('employees', models.ManyToManyField(blank=True, related_name='employees', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UseScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('scenario', models.TextField(help_text='Write a scenario where email will be sent..')),
                ('POI', models.CharField(help_text='person of interest', max_length=255)),
                ('poi_email', models.EmailField(max_length=254)),
                ('link_field', models.URLField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
