# Generated by Django 4.2.7 on 2023-12-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_departments_company_departments_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='color',
            field=models.CharField(default='color', max_length=7),
        ),
    ]
