# Generated by Django 4.2.7 on 2024-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progress',
            name='progress_bar',
            field=models.IntegerField(default=0),
        ),
    ]
