# Generated by Django 4.2.7 on 2023-12-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_departments_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usescenario',
            name='user',
        ),
    ]
