# Generated by Django 4.2.7 on 2024-02-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_progress_level_progress_progress_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_clicks', models.IntegerField(default=0)),
                ('reported', models.IntegerField(default=0)),
                ('progress_bar', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.departments')),
            ],
        ),
    ]
