# Generated by Django 4.2.7 on 2023-12-09 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_company_user_remove_usescenario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='incidents',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.departments')),
            ],
        ),
    ]
