# Generated by Django 4.2.7 on 2023-12-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_departments_incidents_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
    ]
