# Generated by Django 4.2.7 on 2023-12-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_employee_company_employee_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
