# Generated by Django 4.2.7 on 2023-12-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_employee_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_created',
            field=models.DateField(auto_created=True),
        ),
    ]
