# Generated by Django 4.2.7 on 2024-01-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_departments_number_of_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usescenario',
            name='company',
        ),
    ]
