# Generated by Django 4.2.7 on 2024-01-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_usescenario_company'),
        ('emailGenerator', '0017_usescenario_alter_emaildocument_scenario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UseScenario',
        ),
    ]
